### ISSUE TITLE
Feature 1: User can create a room with a name

### ISSUE THREAD

**Issue by a-plasencia** [a-plasencia/Final-Project#1]
⚙️ Feature

User can create a room with a name

## 📐 Functionality

An input form will allow the user to write a room name in

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 10 55 47 AM](https://user-images.githubusercontent.com/36422433/163851726-3d4094d6-41c3-4b22-a7de-6845f06982a5.png)
![Screen Shot 2022-04-18 at 10 55 37 AM](https://user-images.githubusercontent.com/36422433/163851732-af4db5d5-c689-4989-83f2-b5295aecf18d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Get the completed database by exporting the schema made on dbd and then importing it into the final project

### ☁️ Server

- [x] Make sure you can listen to the server 
- [x] Update `server/index.js` to be able to receive post requests that can update the database
- [x] Test with HTTPie
- [x] Have an error prepared if the submission they tried to send was empty
- [x] Handle any other errors and respond to the client

### ⚡ Client

- [x] Setup React-Bootstrap and test that it's working
- [x] Have the component be a react bootstrap form element with 3 inputs.  A Room name, a username, and a youtube link
- [x] Make sure the button type is submit
- [x] Verify that the user is not submitting any empty
- [x] On submit send a post request and update the database with that information.
- [x] Add a navbar

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
](https://youtu.be/xxbJdwL754E)
